apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptest
spec:
  selector:
    matchLabels:
      app: apptest
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: apptest
    spec:
      containers:
      - name: apptest
        image: public.ecr.aws/n5h8m9x0/k8s:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
              - name: Custom-Header
                value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: apptest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
